# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'failplay.ui'
# Updated for PyQt5

from PyQt5 import QtCore, QtGui, QtWidgets

def _translate(context, text, disambig=None):
    return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(632, 662)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lstLibrary = LibraryView(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.lstLibrary.sizePolicy().hasHeightForWidth())
        self.lstLibrary.setSizePolicy(sizePolicy)
        self.lstLibrary.setDragEnabled(True)
        self.lstLibrary.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.lstLibrary.setObjectName("lstLibrary")
        self.verticalLayout_2.addWidget(self.lstLibrary)
        self.leLibraryFilter = QtWidgets.QLineEdit(self.layoutWidget)
        self.leLibraryFilter.setObjectName("leLibraryFilter")
        self.verticalLayout_2.addWidget(self.leLibraryFilter)
        self.lstPlaylist = QtWidgets.QTableView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstPlaylist.sizePolicy().hasHeightForWidth())
        self.lstPlaylist.setSizePolicy(sizePolicy)
        self.lstPlaylist.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.lstPlaylist.setAcceptDrops(True)
        self.lstPlaylist.setDragEnabled(True)
        self.lstPlaylist.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.lstPlaylist.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.lstPlaylist.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.lstPlaylist.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.lstPlaylist.setObjectName("lstPlaylist")
        self.verticalLayout_4.addWidget(self.splitter)
        self.verticalLayout_viz = QtWidgets.QVBoxLayout()
        self.verticalLayout_viz.setObjectName("verticalLayout_viz")
        self.ledViz = LedVizWidget(self.centralwidget)
        self.ledViz.setObjectName("ledViz")
        self.verticalLayout_viz.addWidget(self.ledViz)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pgbSongProgress = QtWidgets.QProgressBar(self.centralwidget)
        self.pgbSongProgress.setProperty("value", 0)
        self.pgbSongProgress.setTextVisible(True)
        self.pgbSongProgress.setInvertedAppearance(False)
        self.pgbSongProgress.setObjectName("pgbSongProgress")
        self.horizontalLayout.addWidget(self.pgbSongProgress)
        self.pgbSongProgressPrev = QtWidgets.QProgressBar(self.centralwidget)
        self.pgbSongProgressPrev.setProperty("value", 0)
        self.pgbSongProgressPrev.setTextVisible(True)
        self.pgbSongProgressPrev.setInvertedAppearance(False)
        self.pgbSongProgressPrev.setObjectName("pgbSongProgressPrev")
        self.horizontalLayout.addWidget(self.pgbSongProgressPrev)
        self.verticalLayout_viz.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_viz)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 632, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "FailPlay"))
        self.leLibraryFilter.setPlaceholderText(_translate("MainWindow", "Search..."))
        self.pgbSongProgress.setFormat(_translate("MainWindow", "Idle"))
        self.pgbSongProgressPrev.setFormat(_translate("MainWindow", "Idle"))

from libraryview import LibraryView
from ledviz import LedVizWidget
