when:
  - event: push
  - event: pull_request
  - event: manual

labels:
  arch: arm64

steps:
  - name: test
    image: debian:bookworm
    commands:
      - apt-get update -qq
      - apt-get install -y -qq make sudo
      - make dep
      - make test
